<project default="devbuild">

	<!-- Simply set the name of the plugin here, e.g. "xyz" or "xyz_importer") instead of "sample" -->
	<property name="name" value="processInspection" />

	<!-- Use this task to let ant copy the compiled jar files to the target folders for development  -->
	<target name="devbuild">
		<exec executable="mvn">
			<arg value="package"/>
		</exec>
        <copy file="module-base/target/plugin-workflow-process-inspection-base.jar" todir="/opt/digiverso/goobi/plugins/workflow/" overwrite="true"/>
        <copy file="module-gui/target/plugin-workflow-process-inspection-gui.jar" todir="/opt/digiverso/goobi/plugins/GUI/" overwrite="true"/>

	</target>

</project>
